# Generated by Django 5.1.2 on 2025-03-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('birthplace', models.CharField(max_length=64)),
                ('artist_fact', models.TextField()),
                ('spouse', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=32)),
                ('score', models.DecimalField(decimal_places=1, max_digits=2)),
                ('release_year', models.IntegerField(verbose_name=4)),
                ('genre', models.CharField(max_length=32)),
                ('artist_name', models.CharField(max_length=32)),
            ],
        ),
    ]
