# Generated by Django 5.1.2 on 2025-03-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='release_year',
            field=models.IntegerField(),
        ),
    ]
