# Generated by Django 5.1.2 on 2025-03-11 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top_songs', '0004_songs_artist_alter_songs_artist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='artist_name',
        ),
    ]
