# Generated by Django 5.1.7 on 2025-04-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URMS_App', '0002_song_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('birthplace', models.CharField(max_length=64)),
                ('artist_fact', models.TextField()),
                ('spouse', models.CharField(max_length=32)),
            ],
        ),
    ]
