# Generated by Django 5.1.7 on 2025-04-26 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URMS_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(max_length=127, null='None'),
            preserve_default='None',
        ),
    ]
