# Generated by Django 5.1.2 on 2025-04-26 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URMS_App', '0004_song_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album_art_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='artists',
            name='artist_fact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artists',
            name='birthplace',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artists',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='artists',
            name='spouse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='URMS_App.artists'),
        ),
        migrations.AlterField(
            model_name='song',
            name='currentRating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='dateAdded',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='song',
            name='totalVotes',
            field=models.IntegerField(default=0),
        ),
    ]
