# Generated by Django 5.1.7 on 2025-04-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URMS_App', '0005_song_album_art_url_alter_artists_artist_fact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='spotify_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='album_art_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
