# Generated by Django 5.1.7 on 2025-03-08 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=254)),
                ('password', models.CharField(max_length=32)),
                ('userID', models.IntegerField()),
                ('isActive', models.BooleanField()),
                ('isAdmin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('album', models.CharField(max_length=127)),
                ('releaseDate', models.DateField()),
                ('dateAdded', models.DateField()),
                ('currentRating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('totalVotes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='login.user')),
            ],
            bases=('login.user',),
        ),
    ]
