# Generated by Django 5.1.7 on 2025-03-08 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_testmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isAdmin',
        ),
    ]
