# Generated by Django 5.1.7 on 2025-03-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_user_isadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(editable=False, max_length=64),
        ),
    ]
