# Generated by Django 5.1.7 on 2025-03-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
