# Generated by Django 5.1.7 on 2025-03-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_user_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.IntegerField(editable=False),
        ),
    ]
