# Generated by Django 5.1.7 on 2025-03-10 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_user_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userID',
        ),
    ]
