# Generated by Django 5.1.7 on 2025-03-11 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_uploadedimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profilePic',
        ),
    ]
