# Generated by Django 5.1.2 on 2025-03-11 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_songs', '0002_alter_songs_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='artist_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='top_songs.artists'),
        ),
    ]
