# Generated by Django 5.1.2 on 2025-03-11 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_songs', '0003_alter_songs_artist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='top_songs.artists'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='artist_name',
            field=models.CharField(max_length=32),
        ),
    ]
